name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-latest, windows-latest] # macos-13: Intel, macos-latest: M1/M2
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          # IntelとApple Silicon用にアーキテクチャを指定
          args: ${{ matrix.os == 'macos-13' && '--x64' || matrix.os == 'macos-latest' && '--arm64' || '' }}